# Generated by Django 5.0.6 on 2024-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=10, unique=True)),
                ('video_title', models.CharField(max_length=255)),
                ('author_name', models.CharField(max_length=255)),
                ('date_of_publish', models.CharField(max_length=255)),
                ('youtube_url', models.URLField()),
                ('time_of_additon', models.DateTimeField()),
            ],
        ),
    ]
