# Generated by Django 5.0.6 on 2024-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.IntegerField(unique=True)),
                ('course_name', models.CharField(max_length=255)),
                ('course_provider', models.CharField(max_length=255)),
                ('course_description', models.TextField()),
                ('course_rating', models.CharField(max_length=255)),
                ('course_language', models.CharField(max_length=255)),
                ('course_duration', models.CharField(max_length=255)),
                ('course_start_date', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('course_url', models.URLField()),
                ('course_subject', models.CharField(max_length=255)),
                ('course_topic', models.CharField(max_length=255)),
                ('insert_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
